### ISSUE TITLE
Title of the page should be present on the top right nav menu

### ISSUE THREAD

**Issue by pierre** [killbill/killbill-docs#210]
From https://docs.killbill.io/latest/userguide_kaui.html;

![image](https://user-images.githubusercontent.com/51940/109830031-00e4b980-7c36-11eb-8daf-21f87ce2912d.png)

**Comment by pierre** [comment]
Alternatively, we could just shade/highlight the title of the manual:

![image](https://user-images.githubusercontent.com/51940/109830736-af88fa00-7c36-11eb-93da-5b98361b3fc8.png)

**Comment by ghost** [comment]
@pierre  or @sbrossie 
The redesign addressed this issue, so we can close this.  
![image](https://user-images.githubusercontent.com/42384068/166504165-8458c2a2-1636-42e3-91e2-06f393992e2f.png)

**Comment by sbrossie** [comment]
@FlowWriter Is this live already - I don't see it?

**Comment by ghost** [comment]
@sbrossie - This issue was something we logged regarding the overall design. We wanted to be sure that the title of the currently displayed document was indicated in some way. We (the designers) completed the redesign, and you can now see the blue line to the left of "Subscription Billing" with the Subscription Guide displayed. Get it? ;-)
