### ISSUE TITLE
New docs site: Width of left nav bar adjustable

### ISSUE THREAD

**Issue by reshmabidikar** [killbill/killbill-docs#506]
Wondering if we should make the width of the left navigation bar adjustable? Currently, it displays as follows for me:

<img width="924" alt="image" src="https://github.com/killbill/killbill-docs/assets/85998496/7126c59f-b7ae-41b1-952a-2b372c31c8a1">

I think it would be good to have the option to make the left navigation bar narrower so the main page content has a larger area for display.

**Comment by pierre** [comment]
It would be nice to also have an option to collapse it on demand.

**Comment by deekant** [comment]
@reshmabidikar @pierre I narrowed down the content part on purpose. According to the UX pattern for the user, it's much more comfortable to read shorter portions of text, up to 800px width (e.g. Stripe docs https://stripe.com/docs/connect/collect-then-transfer-guide or any blog article on https://medium.com/) rather than longer (current Kill Bill Docs pages).

@reshmabidikar I assume you took a screenshot from 1180px width? And at this point, we still can leave both - 800px of content and 320px of a sidebar. I just need to make the content fill all space at this breakpoint as well. Does it make sense?

**Comment by reshmabidikar** [comment]
@deekant, not sure, I completely follow. I believe my display resolution is `1920x1080`. So are you saying we can still make the content fill out all the space?

**Comment by deekant** [comment]
@reshmabidikar @pierre Here I explain a bit more about the content width and left sidebar, please check and let me know if we still need to make the sidebar adjustable or collapsable https://www.loom.com/share/6e8eabb291a5487186d86a8fba7bec03?sid=cc66e060-f9ff-4d1a-801e-0a2852b6ec82

**Comment by reshmabidikar** [comment]
https://github.com/killbill/killbill-docs/pull/515 addresses this. As discussed on Slack, the left nav bar should be made collapsible as part of this task. This works as expected, closing this issue.
