### ISSUE TITLE
Database Migrations DDL link out of date

### ISSUE THREAD

**Issue by ccostes** [killbill/killbill-docs#63]
The database migrations guide (userguide/tutorials/database_migrations.adoc) has a link for the "latest" ddl file, along with a link to the http://killbill.io/downloads/ page. Both of these sources contain the DDL file for Kill Bill version 0.18, which is out of date. (the whole downloads page is for version 0.18, but that's a separate issue)

Might be best to just point to the github source (which is actually the first result if you google "kill bill ddl") to avoid needing to update it for each release.

**Comment by pierre** [comment]
> (the whole downloads page is for version 0.18, but that's a separate issue)

Oops 🙊This is a legacy page, it shouldn't be referenced anymore.

> Might be best to just point to the github source (which is actually the first result if you google "kill bill ddl") to avoid needing to update it for each release.

Because of our project structure, there isn't a single DDL file (not sure which link Google shows you, but I'm seeing https://docs.killbill.io/0.16/getting_started.html 😕).

I've fixed the script generating the directory in 39d992ce. PR: https://github.com/killbill/killbill-docs/pull/64.

Thanks for the report!

Related: https://github.com/killbill/killbill-cloud/issues/66
